services:
  user-service:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - ORDER_SERVICE_URL=http://order-service:3003
    command: ["bun", "user-service/app.js"]
    networks:
      - microservice-network

networks:
  microservice-network:
    external: true
    name: microservice-network
